---
- hosts: rails
  remote_user: root
  sudo: yes
  gather_facts: no
  pre_tasks:
    - name: apt-get update
      raw: sudo apt-get update
    - name: 'install python2'
      raw: sudo apt-get -y install python-minimal
  tasks:
  - name: Download pip
    get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/get-pip.py
  - name: Install pip
    command: python /get-pip.py
  - name: Delete pip installation file
    file: dest=/get-pip.py state=absent
