---
# All roles are installed from Ansible Galaxy
- src: manala.git
- src: geerlingguy.passenger
- src: geerlingguy.nodejs
- src: DavidWittman.redis
- src: spitfast.rbenv
- src: ANXS.postgresql
- src: kamaln7.swapfile
